### ISSUE TITLE
Contribution query

### ISSUE THREAD

**Issue by JDRanpariya** [lutfumertceylan/top25-parameter#7]
Hi Lutfumertcelyan, 
I watched Jason's talk and in param discovery he talks about this project along with others gf-patterns list. 

So I'm going through all the repos and combining all. For example I went for all lfi params and combined | sort -u. Is it fine If I make PR to your gf patterns(actually it's 34). 

I understand the name is top25 but for gf-patterns I think it should be fine. anyway list of top25 and gf will be kind of separate.

It would be nice to have top25 param(I think use-case is when actively bug hunting and looking at post requests etc) along with ultimate list of gf patterns.

**Comment by lutfumertceylan** [comment]
Hi JDRanpariya,

You can have **top25-parameter** for this project. 
If you want it, if I have unwittingly helped you with your new project with Jason, I will gladly accept your credit and be very pleased :-)
